name: "Build & Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # setup java version 17
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'

      - name: flutter action  
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'
          channel: 'stable'
          cache: true
      
      - name: flutter version
        run: flutter --version

      # get packages
      - name: Get packages
        run: flutter pub get
      
      # test
      - name: Test app
        run: flutter test

      # build
      - name: Build app
        run: flutter build apk

      - run: flutter build appbundle

      # release
      - name: Release app
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/*.apk'
          token: ${{ secrets.GITHUB_TOKEN }}

      